{:user { :plugins [[cider/cider-nrepl "0.8.2"]
                   [lein-ancient "0.5.5"]
                   [lein-annotations "0.1.0"]
                   [lein-bikeshed "0.2.0"]
                   [lein-marginalia "0.8.0"]
                   [lein-kibit "0.0.8"]
                   [codox "0.8.10"]
                   [lein-midje "3.1.3"]
                   [jonase/eastwood "0.2.1"]
                   [lein-pprint "1.1.2"]
                   [com.aphyr/prism "0.1.2"]]
        :dependencies [[slamhound "1.5.5"]
                       [com.aphyr/prism "0.1.2"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
